credentials_usernames_ondra_email = 'michal.hruska@keboola.com'
credentials_usernames_ondra_name = 'Michal Hruska'
credentials_usernames_ondra_password = '$2b$12$RqSbpU.KwaXJqZ0Xivh/SOmiRCvnqjqI1g95p7Yf9katK3UwgJAgC'
keboola_host = 'keboola.west-europe.azure.snowflakecomputing.com',
keboola_warehouse = 'KEBOOLA_PROD_SMALL',
keboola_database = 'KEBOOLA_1255',
keboola_schema = 'WORKSPACE_42438928',
keboola_user = 'KEBOOLA_WORKSPACE_42438928',
keboola_password = 'gS4yNcR3DXkZsDARC9kcA3niyXBiWN57',
keboola_account = 'keboola',
keboola_backend = 'snowflake'